name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           # This is needed to retrieve all commits history in a single branch with 200 being the maximum fetch-depth
           # using fetch-depth "100" gets all commit history for all branches and tags in the repository which we didn't need and felt was an expensive operation.
           persist-credentials: false
           fetch-depth: "100"
             
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.PAT_ACCESS}} #This token is needed to grant GitHub Action persmission to push tags to protected branch
